// apps/demo-react/src/App.tsx
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import { AIComponent } from "@adaptive-ui/components/react";

function App() {
  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <AIComponent
        intent="ProductCard"
        data={{
          productName: "Premium Headphones",
          price: "$299",
          features: [
            "High-fidelity sound",
            "Noise cancellation",
            "Comfort fit",
          ],
        }}
      />
    </>
  );
}

export default App;

// apps/demo-svelte/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import viteLogo from '/vite.svg'
  import { AIComponent } from "@adaptive-ui/components/svelte";
</script>

<main>
  <div>
    <a href="https://vite.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

    <AIComponent
        intent="ProductCard"
        data={{
          productName: "Premium Headphones",
          price: "$299",
          features: [
            "High-fidelity sound",
            "Noise cancellation",
            "Comfort fit",
          ],
        }}
      />
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
</style>
