// packages/components/src/svelte/AIComponent.svelte
<script>
  import { onMount } from 'svelte';
  import { generateComponent } from "@adaptive-ui/client";

  export let intent;
  export let data;

  let generating = true;
  let html = "";
  let error = "";

  onMount(async () => {
    try {
      const generatedHtml = await generateComponent(intent, data, {
        language: "en",
        persona: "default",
        timestamp: 18232183123127,
        sessionId: "demo-session",
      });
      html = generatedHtml;
      generating = false;
    } catch (err) {
      error = err.message || "Error generating AIComponent";
      generating = false;
    }
  });
</script>

{#if generating}
  <div>Generating...</div>
{:else if error}
  <div class="text-red-600">{error}</div>
{:else}
  <div>{@html html}</div>
{/if}

// packages/components/src/vue/AIComponent.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { generateComponent } from "@adaptive-ui/client";

interface AIComponentProps {
  intent: string;
  data: any;
}

const props = defineProps<AIComponentProps>();

const generating = ref(true);
const html = ref("");
const error = ref("");

onMounted(() => {
  generateComponent(props.intent, props.data, {
    language: "en",
    persona: "default",
    timestamp: 18232183123127,
    sessionId: "demo-session",
  })
    .then((generatedHtml) => {
      html.value = generatedHtml;
      generating.value = false;
    })
    .catch((err: any) => {
      error.value = err.message || "Error generating AIComponent";
      generating.value = false;
    });
});
</script>

<template>
  <div v-if="generating">Generating...</div>
  <div v-else-if="error" class="text-red-600">{{ error }}</div>
  <div v-else v-html="html"></div>
</template>
