// apps/demo-svelte/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import viteLogo from '/vite.svg'
  import { AIComponent } from "@adaptive-ui/components/svelte";
</script>

<main>
  <div>
    <a href="https://vite.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

    <AIComponent
        intent="ProductCard"
        data={{
          productName: "Premium Headphones",
          price: "$299",
          features: [
            "High-fidelity sound",
            "Noise cancellation",
            "Comfort fit",
          ],
        }}
      />
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
</style>

// apps/demo-vue/src/App.vue
<script setup lang="ts">
import { AIComponent } from "@adaptive-ui/components/vue";
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <h1>Vite + Vue</h1>
  <AIComponent
    intent="Create a user profile card component"
    :data="{
      name: 'John Doe',
      avatar: 'https://randomuser.me/api/portraits/men/75.jpg',
      bio: 'A passionate developer who loves coding and coffee.',
      social: {
        twitter: 'johndoe',
        github: 'johndoe',
      },
    }"
  />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
