// packages/components/src/vue/AIComponent.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { generateComponent } from "@adaptive-ui/client";

interface AIComponentProps {
  intent: string;
  data: any;
}

const props = defineProps<AIComponentProps>();

const generating = ref(true);
const html = ref("");
const error = ref("");

onMounted(() => {
  generateComponent(props.intent, props.data, {
    language: "en",
    persona: "default",
    timestamp: 18232183123127,
    sessionId: "demo-session",
  })
    .then((generatedHtml) => {
      html.value = generatedHtml;
      generating.value = false;
    })
    .catch((err: any) => {
      error.value = err.message || "Error generating AIComponent";
      generating.value = false;
    });
});
</script>

<template>
  <div v-if="generating">Generating...</div>
  <div v-else-if="error" class="text-red-600">{{ error }}</div>
  <div v-else v-html="html"></div>
</template>

// src/neurify/components/AIComponent.tsx
import { component$, PropsOf } from "@builder.io/qwik";
import { useGenerateComponent } from "~/neurify/ai/generate-component";
import { AIGenerating } from "~/neurify/components/AIGenerating";

type AIComponentProps = {
  intent: string;
  data: any;
} & PropsOf<"div">;

export const AIComponent = component$<AIComponentProps>((props) => {
  const { intent, data, ...rest } = props;
  const { generating, error, html } = useGenerateComponent(intent, data);

  if (generating.value) {
    return <AIGenerating />;
  }

  if (error.value) {
    return (
      <div {...rest} class="text-red-600">
        Error: {error.value}
      </div>
    );
  }

  return <div {...rest} dangerouslySetInnerHTML={html.value} />;
});
